### ISSUE TITLE
Add support for prettier 3.0

### ISSUE THREAD

**Issue by curthipster** [hosseinmd/prettier-plugin-jsdoc#196] opened 2023-07-18 23:26 UTC
prettier fails with error after upgrading from 2.8.8 to 3.0.0:

```
> prettier . --check

Checking formatting...
[error] Cannot read properties of undefined (reading 'filter')
```

In case it helps, `prettier-plugin-tailwindcss` had a similar [issue](https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/176#issuecomment-1621926950).

**Comment by yf-yang** [comment] 2023-07-19 03:46
Seems #195 is the WIP

**Comment by auvred** [comment] 2023-07-19 10:46
Duplicate of https://github.com/hosseinmd/prettier-plugin-jsdoc/issues/194

**Comment by hosseinmd** [comment] 2023-07-19 11:04
Fixed https://github.com/hosseinmd/prettier-plugin-jsdoc/pull/195

**Closed by hosseinmd** 2023-07-19 11:04 UTC

**Comment by curthipster** [comment] 2023-07-19 18:03
Oh, thank you and sorry for the noise. I swear I searched but apparently didn't look hard enough.
